apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-{{ .Release.Name }}-svc
spec:
  type: {{ .Values.service.type }}
  ports:
  {{- include "Service.type" . | indent 2 }}
  selector:
    {{- include "Label.Generator" . | indent 4 }}